// Create Site types:
export const PUBLISH_SITE_REQUESTED = 'sites/PUBLISH_SITE_REQUESTED';
export const PUBLISH_SITE_STATUS_CHANGED = 'sites/PUBLISH_SITE_STATUS_CHANGED';
export const PUBLISH_SITE_SUCCEED = 'sites/PUBLISH_SITE_SUCCEED';
export const PUBLISH_SITE_FAILED = 'sites/PUBLISH_SITE_FAILED';
