export const SUBSCRIPTION_STARTED = 'subscriptions/SUBSCRIPTION_STARTED';
export const SUBSCRIPTION_MODIFIED = 'subscriptions/SUBSCRIPTION_MODIFIED';
export const SUBSCRIPTION_READY = 'subscriptions/SUBSCRIPTION_READY';
export const SUBSCRIPTION_FAILED = 'subscriptions/SUBSCRIPTION_FAILED';
export const SUBSCRIPTION_STOPPED = 'subscriptions/SUBSCRIPTION_STOPPED';
// getCatIndex types:
export const GOTTEN_CATEGORIES_INDEX = 'settings/GOTTEN_CATEGORIES_INDEX';
export const MISSING_CATEGORIES_INDEX = 'settings/MISSING_CATEGORIES_INDEX';
