export const CREATE_SITE_REQUESTED = 'sites/CREATE_SITE_REQUESTED';
export const CREATE_SITE_STATUS_CHANGED = 'sites/CREATE_SITE_STATUS_CHANGED';
export const CREATE_SITE_SUCCEED = 'sites/CREATE_SITE_SUCCEED';
export const CREATE_SITE_FAILED = 'sites/CREATE_SITE_FAILED';

export const SITES_COLLECTION_STARTED = 'sites/SITES_COLLECTION_STARTED';
export const SITES_COLLECTION_MODIFIED = 'sites/SITES_COLLECTION_MODIFIED';
export const SITES_COLLECTION_READY = 'sites/SITES_COLLECTION_READY';
export const SITES_COLLECTION_FAILED = 'sites/SITES_COLLECTION_FAILED';
export const SITES_COLLECTION_STOPPED = 'sites/SITES_COLLECTION_STOPPED';

export { LOGIN_SUCCEED, LOGOUT_SUCCEED } from '../dependencies';
