export const CREATE_SITE_REQUESTED = 'sites/CREATE_SITE_REQUESTED';
export const CREATE_SITE_STATUS_CHANGED = 'sites/CREATE_SITE_STATUS_CHANGED';
export const CREATE_SITE_SUCCEED = 'sites/CREATE_SITE_SUCCEED';
export const CREATE_SITE_FAILED = 'sites/CREATE_SITE_FAILED';
export const SITES_COLLECTION_MODIFIED = 'sites/SITES_COLLECTION_MODIFIED';

export { LOGIN_SUCCEED, LOGOUT_SUCCEED } from '../dependencies';
