export const THEME_CHANGE_REQUESTED = 'build/THEME_CHANGE_REQUESTED';
export const THEME_CHANGE_SUCCEED = 'build/THEME_CHANGE_SUCCEED';
export const THEME_CHANGE_FAILED = 'build/THEME_CHANGE_FAILED';

export const THEME_DOWNLOAD_REQUESTED = 'build/THEME_DOWNLOAD_REQUESTED';
export const THEME_DOWNLOAD_SUCCEED = 'build/THEME_DOWNLOAD_SUCCEED';
export const THEME_DOWNLOAD_FAILED = 'build/THEME_DOWNLOAD_FAILED';

export const EXTENSION_LOAD_REQUESTED = 'build/EXTENSION_LOAD_REQUESTED';
export const EXTENSION_LOAD_SUCCEED = 'build/EXTENSION_LOAD_SUCCEED';
export const EXTENSION_LOAD_FAILED = 'build/EXTENSION_LOAD_FAILED';

export const EXTENSION_DOWNLOAD_REQUESTED = 'build/EXTENSION_DOWNLOAD_REQUESTED';
export const EXTENSION_DOWNLOAD_SUCCEED = 'build/EXTENSION_DOWNLOAD_SUCCEED';
export const EXTENSION_DOWNLOAD_FAILED = 'build/EXTENSION_DOWNLOAD_FAILED';

export const PACKAGES_ADDITION_REQUESTED = 'build/PACKAGES_ADDITION_REQUESTED';
export const PACKAGES_ADDITION_SUCCEED = 'build/PACKAGES_ADDITION_SUCCEED';
export const PACKAGES_ADDITION_FAILED = 'build/PACKAGES_ADDITION_FAILED';

export const PACKAGES_DOWNLOAD_REQUESTED = 'build/PACKAGES_DOWNLOAD_REQUESTED';
export const PACKAGES_DOWNLOAD_SUCCEED = 'build/PACKAGES_DOWNLOAD_SUCCEED';
export const PACKAGES_DOWNLOAD_FAILED = 'build/PACKAGES_DOWNLOAD_FAILED';

export const PACKAGES_LOAD_REQUESTED = 'build/PACKAGES_LOAD_REQUESTED';
export const PACKAGES_LOAD_SUCCEED = 'build/PACKAGES_LOAD_SUCCEED';
export const PACKAGES_LOAD_FAILED = 'build/PACKAGES_LOAD_FAILED';
