export const RESPONSE_NOT_200 = 'RESPONSE_NOT_200';
export const WP_API_NOT_FOUND = 'WP_API_NOT_FOUND';
export const WORONA_PLUGIN_NOT_FOUND = 'WORONA_PLUGIN_NOT_FOUND';
export const SITEID_DONT_MATCH = 'SITEID_DONT_MATCH';
export const TIMEOUT = 'TIMEOUT';
export const METEOR_USER_NOT_LOGGED_IN = 'NOT_LOGGED_IN';
