export const SUBSCRIPTION_STARTED = 'subscriptions/SUBSCRIPTION_STARTED';
export const COLLECTION_MODIFIED = 'subscriptions/COLLECTION_MODIFIED';
export const SUBSCRIPTION_READY = 'subscriptions/SUBSCRIPTION_READY';
export const SUBSCRIPTION_FAILED = 'subscriptions/SUBSCRIPTION_FAILED';
export const SUBSCRIPTION_STOPPED = 'subscriptions/SUBSCRIPTION_STOPPED';
