// Save Settings types:
export const SAVE_SETTING_REQUESTED = 'sites/SAVE_SETTING_REQUESTED';
export const SAVE_SETTING_STATUS_CHANGED = 'sites/SAVE_SETTING_STATUS_CHANGED';
export const SAVE_SETTING_SUCCEED = 'sites/SAVE_SETTING_SUCCEED';
export const SAVE_SETTING_FAILED = 'sites/SAVE_SETTING_FAILED';
