// Save Settings types:
export const SAVE_SETTING_REQUESTED = 'settings/SAVE_SETTING_REQUESTED';
export const SAVE_SETTING_STATUS_CHANGED = 'settings/SAVE_SETTING_STATUS_CHANGED';
export const SAVE_SETTING_SUCCEED = 'settings/SAVE_SETTING_SUCCEED';
export const SAVE_SETTING_FAILED = 'settings/SAVE_SETTING_FAILED';

export const DEFAULT_SETTINGS_NEEDED = 'settings/DEFAULT_SETTINGS_NEEDED';
