// Save Settings types:
export const SAVE_SETTINGS_REQUESTED = 'settings/SAVE_SETTINGS_REQUESTED';
export const SAVE_SETTINGS_STATUS_CHANGED = 'settings/SAVE_SETTINGS_STATUS_CHANGED';
export const SAVE_SETTINGS_SUCCEED = 'settings/SAVE_SETTINGS_SUCCEED';
export const SAVE_SETTINGS_FAILED = 'settings/SAVE_SETTINGS_FAILED';

export const DEFAULT_SETTINGS_NEEDED = 'settings/DEFAULT_SETTINGS_NEEDED';
