export const CREATE_SITE_REQUESTED = 'sites/CREATE_SITE_REQUESTED';
export const CREATE_SITE_STATUS_CHANGED = 'sites/CREATE_SITE_STATUS_CHANGED';
export const CREATE_SITE_SUCCEED = 'sites/CREATE_SITE_SUCCEED';
export const CREATE_SITE_FAILED = 'sites/CREATE_SITE_FAILED';
