export const CORE_PACKAGES_REQUESTED = 'build/CORE_PACKAGES_REQUESTED';
export const CORE_PACKAGES_SUCCEED = 'build/CORE_PACKAGES_SUCCEED';
export const CORE_PACKAGES_FAILED = 'build/CORE_PACKAGES_FAILED';

export const PACKAGES_ADDITION_REQUESTED = 'build/PACKAGES_ADDITION_REQUESTED';
export const PACKAGES_ADDITION_SUCCEED = 'build/PACKAGES_ADDITION_SUCCEED';
export const PACKAGES_ADDITION_FAILED = 'build/PACKAGES_ADDITION_FAILED';

export const PACKAGES_DOWNLOAD_REQUESTED = 'build/PACKAGES_DOWNLOAD_REQUESTED';
export const PACKAGES_DOWNLOAD_SUCCEED = 'build/PACKAGES_DOWNLOAD_SUCCEED';
export const PACKAGES_DOWNLOAD_FAILED = 'build/PACKAGES_DOWNLOAD_FAILED';

export const PACKAGE_DOWNLOAD_REQUESTED = 'build/PACKAGE_DOWNLOAD_REQUESTED';
export const PACKAGE_DOWNLOAD_SUCCEED = 'build/PACKAGE_DOWNLOAD_SUCCEED';
export const PACKAGE_DOWNLOAD_FAILED = 'build/PACKAGE_DOWNLOAD_FAILED';

export const PACKAGES_LOAD_REQUESTED = 'build/PACKAGES_LOAD_REQUESTED';
export const PACKAGES_LOAD_SUCCEED = 'build/PACKAGES_LOAD_SUCCEED';
export const PACKAGES_LOAD_FAILED = 'build/PACKAGES_LOAD_FAILED';

export const THEME_CHANGE_REQUESTED = 'build/THEME_CHANGE_REQUESTED';
export const THEME_CHANGE_STARTED = 'build/THEME_CHANGE_STARTED';
export const THEME_CHANGE_SUCCEED = 'build/THEME_CHANGE_SUCCEED';
export const THEME_CHANGE_FAILED = 'build/THEME_CHANGE_FAILED';
