export const CORE_PACKAGES_REQUESTED = 'build/CORE_PACKAGES_REQUESTED';
export const CORE_PACKAGES_SUCCEED = 'build/CORE_PACKAGES_SUCCEED';
export const CORE_PACKAGES_FAILED = 'build/CORE_PACKAGES_FAILED';

export const PACKAGES_ADDITION_REQUESTED = 'build/PACKAGES_ADDITION_REQUESTED';
export const PACKAGES_ADDITION_SUCCEED = 'build/PACKAGES_ADDITION_SUCCEED';
export const PACKAGES_ADDITION_FAILED = 'build/PACKAGES_ADDITION_FAILED';

export const PACKAGES_DOWNLOAD_REQUESTED = 'build/PACKAGES_DOWNLOAD_REQUESTED';
export const PACKAGES_DOWNLOAD_SUCCEED = 'build/PACKAGES_DOWNLOAD_SUCCEED';
export const PACKAGES_DOWNLOAD_FAILED = 'build/PACKAGES_DOWNLOAD_FAILED';

export const PACKAGE_DOWNLOAD_REQUESTED = 'build/PACKAGE_DOWNLOAD_REQUESTED';
export const PACKAGE_DOWNLOAD_SUCCEED = 'build/PACKAGE_DOWNLOAD_SUCCEED';
export const PACKAGE_DOWNLOAD_FAILED = 'build/PACKAGE_DOWNLOAD_FAILED';

export const PACKAGES_LOAD_REQUESTED = 'build/PACKAGES_LOAD_REQUESTED';
export const PACKAGES_LOAD_SUCCEED = 'build/PACKAGES_LOAD_SUCCEED';
export const PACKAGES_LOAD_FAILED = 'build/PACKAGES_LOAD_FAILED';

export const PACKAGE_LOAD_REQUESTED = 'build/PACKAGE_LOAD_REQUESTED';
export const PACKAGE_LOAD_SUCCEED = 'build/PACKAGE_LOAD_SUCCEED';
export const PACKAGE_LOAD_FAILED = 'build/PACKAGE_LOAD_FAILED';

export const THEME_LOAD_REQUESTED = 'build/THEME_LOAD_REQUESTED';
export const THEME_LOAD_STARTED = 'build/THEME_LOAD_STARTED';
export const THEME_CSS_LOAD_REQUESTED = 'build/THEME_CSS_LOAD_REQUESTED';
export const THEME_CSS_LOAD_SUCCEED = 'build/THEME_CSS_LOAD_SUCCEED';
export const THEME_CSS_LOAD_FAILED = 'build/THEME_CSS_LOAD_FAILED';
export const THEME_HTML_LOAD_REQUESTED = 'build/THEME_HTML_LOAD_REQUESTED';
export const THEME_HTML_LOAD_SUCCEED = 'build/THEME_HTML_LOAD_SUCCEED';
export const THEME_HTML_LOAD_FAILED = 'build/THEME_HTML_LOAD_FAILED';
export const THEME_LOAD_SUCCEED = 'build/THEME_LOAD_SUCCEED';
export const THEME_LOAD_FAILED = 'build/THEME_LOAD_FAILED';
