export const CORE_PACKAGES_REQUESTED = 'build/CORE_PACKAGES_REQUESTED';
export const CORE_PACKAGES_SUCCEED = 'build/CORE_PACKAGES_SUCCEED';
export const CORE_PACKAGES_FAILED = 'build/CORE_PACKAGES_FAILED';

export const PACKAGE_ACTIVATION_REQUESTED = 'build/PACKAGE_ACTIVATION_REQUESTED';
export const PACKAGE_ACTIVATION_SUCCEED = 'build/PACKAGE_ACTIVATION_SUCCEED';
export const PACKAGE_ACTIVATION_FAILED = 'build/PACKAGE_ACTIVATION_FAILED';

export const PACKAGE_DEACTIVATION_REQUESTED = 'build/PACKAGE_DEACTIVATION_REQUESTED';
export const PACKAGE_DEACTIVATION_SUCCEED = 'build/PACKAGE_DEACTIVATION_SUCCEED';
export const PACKAGE_DEACTIVATION_FAILED = 'build/PACKAGE_DEACTIVATION_FAILED';

export const PACKAGE_DOWNLOAD_REQUESTED = 'build/PACKAGE_DOWNLOAD_REQUESTED';
export const PACKAGE_DOWNLOAD_SUCCEED = 'build/PACKAGE_DOWNLOAD_SUCCEED';
export const PACKAGE_DOWNLOAD_FAILED = 'build/PACKAGE_DOWNLOAD_FAILED';

export const PACKAGE_LOAD_REQUESTED = 'build/PACKAGE_LOAD_REQUESTED';
export const PACKAGE_LOAD_SUCCEED = 'build/PACKAGE_LOAD_SUCCEED';
export const PACKAGE_LOAD_FAILED = 'build/PACKAGE_LOAD_FAILED';

export const PACKAGE_ASSETS_LOAD_REQUESTED = 'build/PACKAGE_ASSETS_LOAD_REQUESTED';
export const PACKAGE_ASSETS_FILE_DOWNLOADED = 'build/PACKAGE_ASSETS_FILE_DOWNLOADED';
export const PACKAGE_ASSETS_LOAD_SUCCEED = 'build/PACKAGE_ASSETS_LOAD_SUCCEED';
export const PACKAGE_ASSETS_LOAD_FAILED = 'build/PACKAGE_ASSETS_LOAD_FAILED';
