export const RELOAD_REDUCERS_REQUESTED = 'store/RELOAD_REDUCERS_REQUESTED';
export const RELOAD_REDUCERS_SUCCEED = 'store/RELOAD_REDUCERS_SUCCEED';
export const RELOAD_REDUCERS_FAILED = 'store/RELOAD_REDUCERS_FAILED';
