// Create Site types:
export const CREATE_SITE_REQUESTED = 'sites/CREATE_SITE_REQUESTED';
export const CREATE_SITE_STATUS_CHANGED = 'sites/CREATE_SITE_STATUS_CHANGED';
export const CREATE_SITE_SUCCEED = 'sites/CREATE_SITE_SUCCEED';
export const CREATE_SITE_FAILED = 'sites/CREATE_SITE_FAILED';
// Delete Site types:
export const DELETE_SITE_REQUESTED = 'sites/DELETE_SITE_REQUESTED';
export const DELETE_SITE_STATUS_CHANGED = 'sites/DELETE_SITE_STATUS_CHANGED';
export const DELETE_SITE_SUCCEED = 'sites/DELETE_SITE_SUCCEED';
export const DELETE_SITE_FAILED = 'sites/DELETE_SITE_FAILED';
// Check Site types:
export const CHECK_SITE_REQUESTED = 'sites/CHECK_SITE_REQUESTED';
export const CHECK_SITE_SUCCEED = 'sites/CHECK_SITE_SUCCEED';
export const CHECK_SITE_FAILED = 'sites/CHECK_SITE_FAILED';
// Create Site types:
export const EDIT_SITE_REQUESTED = 'sites/EDIT_SITE_REQUESTED';
export const EDIT_SITE_STATUS_CHANGED = 'sites/EDIT_SITE_STATUS_CHANGED';
export const EDIT_SITE_SUCCEED = 'sites/EDIT_SITE_SUCCEED';
export const EDIT_SITE_FAILED = 'sites/EDIT_SITE_FAILED';
