export const TOGGLE_MOBILE_MENU = 'bulma/TOGGLE_MOBILE_MENU';
export const CLOSE_MOBILE_MENU = 'bulma/CLOSE_MOBILE_MENU';

export const TOGGLE_TERMS_AND_CONDITIONS = 'bulma/TOGGLE_TERMS_AND_CONDITIONS';
export const CLOSE_TERMS_AND_CONDITIONS = 'bulma/CLOSE_TERMS_AND_CONDITIONS';

export const TOGGLE_SITEHOME_MOBILE_MENU = 'bulma/TOGGLE_SITEHOME_MOBILE_MENU';
